import Mongoose from 'mongoose';
Mongoose.Promise = global.Promise;
let db : any = {};
db.mongoose = Mongoose;
db.user = require("./user.model").default(Mongoose);
db.role = require("./role.model").default(Mongoose);
db.comment = require("./comment.model").default(Mongoose);
db.post = require("./post.model").default(Mongoose);
db.postCategory = require("./postCategory.model").default(Mongoose);
db.ROLES = ["user", "admin", "moderator"];
export default db;