const mongoose = require('mongoose');
mongoose.Promise = global.Promise;
let db : any = {};
db.mongoose = mongoose;
db.user = require("./user.model").default(mongoose);
db.role = require("./role.model").default(mongoose);
db.comment = require("./comment.model").default(mongoose);
db.post = require("./post.model").default(mongoose);
db.postCategory = require("./postCategory.model").default(mongoose);
db.ROLES = ["user", "admin", "moderator"];
export default db;